baseURL = 'https://aiclr.github.io'
languageCode = 'en-us'
title = 'aiclr'
theme = 'bougainvillea'
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 2
[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Books'
    pageRef = '/books'
    weight = 40
  [[menus.main]]
    name = 'Develop'
    pageRef = '/develop'
    weight = 20
  [[menus.main]]
    name = 'OS'
    pageRef = '/os'
    weight = 50
  [[menus.main]]
    name = 'Software'
    pageRef = '/software'
    weight = 60
  [[menus.main]]
    name = 'Tools'
    pageRef = '/tools'
    weight = 30
  [[menus.footer]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.footer]]
    name = 'Books'
    pageRef = '/books'
    weight = 40
  [[menus.footer]]
    name = 'Develop'
    pageRef = '/develop'
    weight = 20
  [[menus.footer]]
    name = 'OS'
    pageRef = '/os'
    weight = 50
  [[menus.footer]]
    name = 'Software'
    pageRef = '/software'
    weight = 60
  [[menus.footer]]
    name = 'Tools'
    pageRef = '/tools'
    weight = 30